services:
  # Extend base services
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    environment:
      POSTGRES_DB: eventr_dev
      POSTGRES_USER: eventr_user
      POSTGRES_PASSWORD: eventr_pass

  localstack:
    extends:
      file: docker-compose.yml
      service: localstack

  mailhog:
    extends:
      file: docker-compose.yml
      service: mailhog

  redis:
    extends:
      file: docker-compose.yml
      service: redis

networks:
  default:
    name: eventr-dev